AcrossTec/SysCredit

SysCredit.Api/Constants/ErrorCategories.cs
SysCredit.Api/Controllers/LoanTypeController.cs
SysCredit.Api/Interfaces/ILoanTypeService.cs
SysCredit.Api/Services/LoanTypeService.cs
SysCredit.Api/Stores/LoanTypeStore.cs
SysCredit.DataTransferObject/Commons/LoanTypeInfo.cs
SysCredit.Models/LoanType.cs
SysCredit.SQLServer/PostDeployments/LoanType.Seed.sql
SysCredit.SQLServer/StoredProcedures/FetchLoanTypes.sql
SysCredit.SQLServer/SysCredit.SQLServer.sqlproj

feat: Get All LoanType Endpoint

---

SysCredit.Api/Constants/ErrorCodePrefix.cs
SysCredit.Api/Controllers/LoanTypeController.cs
SysCredit.Api/Extensions/ValidatorExtensions.cs
SysCredit.Api/Interfaces/ILoanTypeService.cs
SysCredit.Api/Services/LoanTypeService.cs
SysCredit.Api/Stores/LoanTypeStore.cs
SysCredit.Api/Validations/LoanTypes/AsyncLoanTypeUniqueNameValidator.cs
SysCredit.Api/Validations/LoanTypes/CreateLoanTypeValidator.cs
SysCredit.Api/ViewModels/LoanTypes/CreateLoanTypeRequest.cs
SysCredit.SQLServer/StoredProcedures/FetchLoanTypeByName.sql
SysCredit.SQLServer/StoredProcedures/InsertLoanType.sql
SysCredit.SQLServer/SysCredit.SQLServer.sqlproj

feat: Insert In LoanType Endpoint

---

SysCredit.Api/Constants/ErrorCodePrefix.cs
SysCredit.Api/Controllers/LoanTypeController.cs
SysCredit.Api/Extensions/ValidatorExtensions.cs
SysCredit.Api/Interfaces/ILoanTypeService.cs
SysCredit.Api/Services/LoanTypeService.cs
SysCredit.Api/Stores/LoanTypeStore.cs
SysCredit.Api/Validations/LoanTypes/AsyncVerifyLoanTypeReferenceValidator.cs
SysCredit.Api/Validations/LoanTypes/DeleteLoanTypeValidator.cs
SysCredit.Api/ViewModels/LoanTypes/DeleteLoanTypeRequest.cs
SysCredit.SQLServer/Functions/VerifyLoanTypeReferences.sql
SysCredit.SQLServer/StoredProcedures/DeleteLoanType.sql
SysCredit.SQLServer/SysCredit.SQLServer.sqlproj

feat: Create Loantype Delete Endpoint

---

SysCredit.Api/Controllers/LoanTypeController.cs
SysCredit.Api/Interfaces/ILoanTypeService.cs
SysCredit.Api/Services/LoanTypeService.cs
SysCredit.Api/Stores/LoanTypeStore.cs
SysCredit.Api/Validations/LoanTypes/UpdateLoanTypeValidator.cs
SysCredit.Api/ViewModels/LoanTypes/UpdateLoanTypeRequest.cs
SysCredit.SQLServer/StoredProcedures/UpdateLoanTypeById.sql
SysCredit.SQLServer/SysCredit.SQLServer.sqlproj

**EN TESTEO - RESOLVIENDO ERRORES!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!**

feat: Create Update LoanType Endpoind

---

SysCredit.Api/Controllers/LoanTypeController.cs
SysCredit.Api/Interfaces/ILoanTypeService.cs
SysCredit.Api/Services/LoanTypeService.cs
SysCredit.Api/Stores/LoanTypeStore.cs
SysCredit.SQLServer/StoredProcedures/FetchLoanTypeById.sql
SysCredit.SQLServer/SysCredit.SQLServer.sqlproj

Crear todo el flujo de trabajo del Endpoint GET: /Api/LoanType/{LoanTypeId}

feat: Create Endpoint  LoanTypeId 

---

SysCredit.Api/Constants/ErrorCategories.cs
SysCredit.Api/Controllers/PaymentFrequencyController.cs
SysCredit.Api/Interfaces/IPaymentFrequencyService.cs
SysCredit.Api/Services/PaymentFrequencyService.cs
SysCredit.Api/Stores/PaymentFrequencyStore.cs
SysCredit.DataTransferObject/Commons/PaymentFrequencyInfo.cs
SysCredit.Models/PaymentFrequency.cs
SysCredit.SQLServer/PostDeployments/PaymentFrequency.Seed.sql
SysCredit.SQLServer/StoredProcedures/FetchPaymentFrequency.sql
SysCredit.SQLServer/SysCredit.SQLServer.sqlproj

feat: Get All PaymentFrequency Endpoint

---

SysCredit.Api/Controllers/PaymentFrequencyController.cs
SysCredit.Api/Interfaces/IPaymentFrequencyService.cs
SysCredit.Api/Services/PaymentFrequencyService.cs
SysCredit.Api/Stores/PaymentFrequencyStore.cs

feat: Get All Complete PaymentFrequency EndPoint

---

SysCredit.Api/Controllers/PaymentFrequencyController.cs
SysCredit.Api/Interfaces/IPaymentFrequencyService.cs
SysCredit.Api/Services/PaymentFrequencyService.cs
SysCredit.Api/Stores/PaymentFrequencyStore.cs
SysCredit.SQLServer/StoredProcedures/FetchPaymentFrequencyById.sql
SysCredit.SQLServer/SysCredit.SQLServer.sqlproj

feat: Create Get PaymentFrequencyById

---

SysCredit.Api/Constants/ErrorCodes.cs
SysCredit.Api/Controllers/PaymentFrequencyController.cs
SysCredit.Api/Extensions/ValidatorExtensions.cs
SysCredit.Api/Interfaces/IPaymentFrequencyService.cs
SysCredit.Api/Services/PaymentFrequencyService.cs
SysCredit.Api/Stores/PaymentFrequencyStore.cs
SysCredit.Api/Validations/PaymentFrequencies/AsyncPaymentFrequencyUniqueNameValidator.cs
SysCredit.Api/Validations/PaymentFrequencies/CreatePaymentFrequencyValidator.cs
SysCredit.Api/Validations/PaymentFrequencies/UpdatePaymentFrequencyValidator.cs
SysCredit.Api/ViewModels/PaymentFrequencies/CreatePaymentFrequencyRequest.cs
SysCredit.Api/ViewModels/PaymentFrequencies/UpdatePaymentFrequencyRequest.cs
SysCredit.SQLServer/StoredProcedures/FetchPaymentFrequencyByName.sql
SysCredit.SQLServer/StoredProcedures/UpdatePaymentFrequency.sql
SysCredit.SQLServer/SysCredit.SQLServer.sqlproj

feat: Update PaymentFrequency EndPoint

---

SysCredit.Api.Tests/IntegrationTests/CustomerEndpointTests.cs
SysCredit.Api/Controllers/CustomerController.cs
SysCredit.Api/Extensions/ValidatorExtensions.cs
SysCredit.Api/Interfaces/Services/ICustomerService.cs
SysCredit.Api/Properties/ErrorCodeMessages.es-NI.resx
SysCredit.Api/Properties/ErrorCodeMessages.resx
SysCredit.Api/Requests/Customers/CustomerIdRequest.cs
SysCredit.Api/Services/CustomerService.cs
SysCredit.Api/Stores/CustomerStore.cs
SysCredit.Api/Stores/GuarantorStore.cs
SysCredit.Api/Validations/Customers/AsyncVerifyIfCustomerExistsByIdValidator.cs
SysCredit.Api/Validations/Customers/CustomerIdRequestValidator.cs
SysCredit.SQLServer/StoredProcedures/Customers/FetchReferencesByCustomerId.sql
SysCredit.sln

feat: Create Get Customer References By Id Endpoint

---

SysCredit.Api/Controllers/CustomerController.cs
SysCredit.Api/Interfaces/Services/ICustomerService.cs
SysCredit.Api/Services/CustomerService.cs
SysCredit.Api/Stores/CustomerStore.cs
SysCredit.SQLServer/StoredProcedures/Customers/FetchGuarantorsByCustomerId.sql
SysCredit.SQLServer/SysCredit.SQLServer.sqlproj

feat: Get All Guarantors by Customer Id

---

SysCredit.Api.Generators/Constants.cs
SysCredit.Api/Controllers/PaymentFrequencyController.cs
SysCredit.Api/Interfaces/Services/IPaymentFrequencyService.cs
SysCredit.Api/Properties/ErrorCodeMessages.es-NI.resx
SysCredit.Api/Properties/ErrorCodeMessages.resx
SysCredit.Api/Requests/PaymentFrequencies/DeletePaymentFrequencyRequest.cs
SysCredit.Api/Services/PaymentFrequencyService.cs
SysCredit.Api/Stores/PaymentFrequencyStore.cs
SysCredit.Api/Validations/PaymentFrequencies/DeletePaymentFrequencyValidator.cs
SysCredit.SQLServer/StoredProcedures/Catalogs/PaymentFrequencies/DeletePaymentFrequency.sql
SysCredit.SQLServer/SysCredit.SQLServer.sqlproj

feat: Delete Payment Frequency By Id

---

SysCredit.Api/Controllers/LoanTypeController.cs
SysCredit.Api/Extensions/ValidatorExtensions.cs
SysCredit.Api/Properties/ErrorCodeMessages.es-NI.resx
SysCredit.Api/Properties/ErrorCodeMessages.resx
SysCredit.Api/Services/LoanTypeService.cs
SysCredit.Api/Stores/LoanTypeStore.cs
SysCredit.Api/Validations/LoanTypes/UpdateLoanTypeValidator.cs
SysCredit.Api/Validations/LoanTypes/VerifyRouteWithLoanTypeIdValidator.cs

feat: Create Validator for Update LoanType by Id

---

SysCredit.Api/Controllers/CustomerController.cs
SysCredit.Api/Interfaces/Services/ICustomerService.cs
SysCredit.Api/Properties/ErrorCodeMessages.resx
SysCredit.Api/Services/CustomerService.cs
SysCredit.Api/Stores/CustomerStore.cs
SysCredit.DataTransferObject/Commons/LoanInfo.cs
SysCredit.SQLServer/StoredProcedures/Customers/FetchLoansByCustomerId.sql
SysCredit.SQLServer/SysCredit.SQLServer.sqlproj

En el controlador **CustomerController** se debe agregar el Endpoint
_GET: /Api/Customer/{CustomerId}/Loans_ 
```csharp
[Validator<CustomerIdRequestValidator>]
public record class CustomerIdRequest : IViewModel
{
public long? CustomerId { get; set; }
public static implicit operator long? CustomerIdRequest(long? CustomerId) => new() { CustomerId = CustomerId };
public statis implicit operator CustomerIdRequest long?(CustomerIdRequest Request) => Request.CustomerId;
}
```
```csharp
public class CustomerIdRequestValidator  : AbstractValidator<CustomerIdRequest>
```
- El _CustomerId_ no debe ser null
- El _CustomerId_ Debe existir en base de datos
- Para esta validación se debe crear un nuevo validador para ser reutilizado  
```csharp
IAsyncEnumerable<LoanInfo> …
```

feat: Adding Get Loans By CostumerId

---

SysCredit.Api/Controllers/CustomerController.cs
SysCredit.Api/Interfaces/Services/ICustomerService.cs
SysCredit.Api/Requests/Customers/GuarantorAndCustomerIdsRequest.cs
SysCredit.Api/Requests/Guarantors/GuarantorIdRequest.cs
SysCredit.Api/Services/CustomerService.cs
SysCredit.Api/Stores/CustomerStore.cs
SysCredit.SQLServer/StoredProcedures/Customers/FetchGuarantorByCustomerIdAndGuarantorId.sql
SysCredit.SQLServer/SysCredit.SQLServer.sqlproj

Get GuarantorDetails By CustomerId And GuarantorId

---

SysCredit.Api/Controllers/RelationshipController.cs
SysCredit.Api/Requests/Relationships/CreateRelationshipRequest.cs
SysCredit.Api/Services/RelationshipService.cs
SysCredit.Api/Stores/RelationshipStore.cs
SysCredit.SQLServer/StoredProcedures/Catalogs/Relationships/FetchInsertRelationship.sql
SysCredit.SQLServer/StoredProcedures/Catalogs/Relationships/InsertRelationship.sql
SysCredit.SQLServer/SysCredit.SQLServer.sqlproj

feat: Post Relationship Endpoint

---

SysCredit.Api/Controllers/RelationshipController.cs
SysCredit.Api/Services/RelationshipService.cs
SysCredit.Api/Stores/RelationshipStore.cs
SysCredit.SQLServer/StoredProcedures/Catalogs/Relationships/DeleteRelationship.sql
SysCredit.SQLServer/SysCredit.SQLServer.sqlproj

feat: Delete Relationship By RelationshipId Endpoint

---

SysCredit.Api/Controllers/GuarantorController.cs
SysCredit.Api/Extensions/ValidatorExtensions.cs
SysCredit.Api/Properties/ErrorCodeMessages.es-NI.resx
SysCredit.Api/Requests/Guarantors/DeleteGuarantorRequest.cs
SysCredit.Api/Services/GuarantorService.cs
SysCredit.Api/Stores/CustomerStore.cs
SysCredit.Api/Stores/GuarantorStore.cs
SysCredit.Api/Validations/Customers/AsyncVerifyifCustomerByGuarantorIdValidator.cs
SysCredit.Api/Validations/Guarantors/DeleteGuarantorValidator.cs
SysCredit.SQLServer/StoredProcedures/Customers/FetchCustomerByGuarantorId.sql
SysCredit.SQLServer/StoredProcedures/Guarantors/DeleteGuarantorById.sql
SysCredit.SQLServer/SysCredit.SQLServer.sqlproj

- Debe recibir por argumento el GuarantorId a marcar como borrado.
- Debe actualizar los campos:
- IsEdit              = true
- IsDelete          = true
- ModifiedDate = CURRENT_TIMESTAMP
- DeletedDate   = CURRENT_TIMESTAMP
- Establecer todos los atributos necesarios
- Establecer todos los atributos necesarios
- Debe recibir como argumento un: `GuarantorId`
- Debe regresar un `bool` para saber si se borró o no
- Acción/Endpoint DeleteGuarantor

feat: Create Guarantor Delete Endpoint

---

SysCredit.Api/Controllers/GuarantorController.cs
SysCredit.Api/Services/GuarantorService.cs
SysCredit.Api/Stores/GuarantorStore.cs

Crear todo el flujo de trabajo del Endpoint GET: /Api/Guarantor/{GuarantorId}

feat: Create Get GuarantorId

---

SysCredit.Api/Controllers/PaymentFrequencyController.cs
SysCredit.Api/Extensions/ReflectionExtensions.cs
SysCredit.Api/Proxies/LoggingAdviceServiceInterceptor.cs
SysCredit.Api/Requests/PaymentFrequencies/DeletePaymentFrequencyRequest.cs
SysCredit.Api/Services/PaymentFrequencyService.cs
SysCredit.Api/Stores/PaymentFrequencyStore.cs
SysCredit.Helpers/Response.cs
SysCredit.SQLServer/StoredProcedures/Catalogs/PaymentFrequencies/DeletePaymentFrequency.sql
SysCredit.SQLServer/StoredProcedures/Catalogs/PaymentFrequencies/FetchPaymentFrequency.sql
SysCredit.SQLServer/StoredProcedures/Catalogs/PaymentFrequencies/FetchPaymentFrequencyById.sql
SysCredit.SQLServer/StoredProcedures/Catalogs/PaymentFrequencies/InsertPaymentFrequency.sql
SysCredit.SQLServer/StoredProcedures/Catalogs/PaymentFrequencies/UpdatePaymentFrequency.sql

fix: Payment Frequency Endpoint Fixed

---

SysCredit.Api/Controllers/PaymentFrequencyController.cs
SysCredit.Api/Controllers/RelationshipController.cs
SysCredit.Api/Requests/Relationships/CreateRelationshipRequest.cs
SysCredit.Api/Requests/Relationships/DeleteRelationshipRequest.cs
SysCredit.Api/Services/PaymentFrequencyService.cs
SysCredit.Api/Services/RelationshipService.cs
SysCredit.Api/Stores/RelationshipStore.cs
SysCredit.Api/Validations/Relationships/CreateRelationshipValidator.cs
SysCredit.Api/Validations/Relationships/DeleteRelationshipValidator.cs
SysCredit.SQLServer/StoredProcedures/Catalogs/PaymentFrequencies/InsertPaymentFrequency.sql
SysCredit.SQLServer/StoredProcedures/Catalogs/Relationships/DeleteRelationship.sql
SysCredit.SQLServer/StoredProcedures/Catalogs/Relationships/FetchRelationship.sql
SysCredit.SQLServer/StoredProcedures/Catalogs/Relationships/FetchRelationshipById.sql
SysCredit.SQLServer/StoredProcedures/Catalogs/Relationships/FetchRelationshipByName.sql
SysCredit.SQLServer/StoredProcedures/Catalogs/Relationships/InsertRelationship.sql

fix: Relationship Endpoint Fixed

---

SysCredit.Api/Properties/ErrorCodeMessages.es-NI.resx
SysCredit.Api/Properties/ErrorCodeMessages.resx
SysCredit.Api/Stores/LoanTypeStore.cs
SysCredit.Api/Validations/Customers/AsyncVerifyifCustomerByGuarantorIdValidator.cs
SysCredit.Api/Validations/Guarantors/AsyncExistsGuarantorValidator.cs
SysCredit.Api/Validations/Guarantors/AsyncGuarantorUniqueEmailValidator.cs
SysCredit.Api/Validations/Guarantors/AsyncGuarantorUniqueIdentificationValidator.cs
SysCredit.Api/Validations/Guarantors/AsyncGuarantorUniquePhoneValidator.cs
SysCredit.Api/Validations/Guarantors/CreateGuarantorValidator.cs
SysCredit.Api/Validations/Guarantors/DeleteGuarantorValidator.cs
SysCredit.Api/Validations/LoanTypes/AsyncVerifyLoanTypeReferenceValidator.cs
SysCredit.Api/Validations/LoanTypes/CreateLoanTypeValidator.cs
SysCredit.Api/Validations/LoanTypes/DeleteLoanTypeValidator.cs
SysCredit.Api/Validations/LoanTypes/UpdateLoanTypeValidator.cs
SysCredit.Api/Validations/PaymentFrequencies/AsyncPaymentFrequencyUniqueNameValidator.cs
SysCredit.Api/Validations/PaymentFrequencies/CreatePaymentFrequencyValidator.cs
SysCredit.Api/Validations/PaymentFrequencies/UpdatePaymentFrequencyValidator.cs
SysCredit.Api/Validations/PaymentFrequencies/VerifyRouteWithPaymentFrequencyIdValidator.cs

feat: Add Error Codes to Guarantor, PaymentFrequency and LoanType Service

---

SysCredit.PostgreSQL/SysCredit.PostgreSQL.vcxproj
SysCredit.PostgreSQL/SysCredit.PostgreSQL.vcxproj.filters
SysCredit.PostgreSQL/Tables/Customer.sql
SysCredit.PostgreSQL/Tables/CustomerGuarantor.sql
SysCredit.PostgreSQL/Tables/CustomerReference.sql
SysCredit.PostgreSQL/Tables/Guarantor.sql
SysCredit.PostgreSQL/Tables/Loan.sql
SysCredit.PostgreSQL/Tables/LoanType.sql
SysCredit.PostgreSQL/Tables/PaymentFrequency.sql
SysCredit.PostgreSQL/Tables/PaymentPlan.sql
SysCredit.PostgreSQL/Tables/PaymentPlanDetails.sql
SysCredit.PostgreSQL/Tables/Reference.sql
SysCredit.PostgreSQL/Tables/Relationship.sql
SysCredit.PostgreSQL/Tables/Role.sql
SysCredit.PostgreSQL/Tables/RoleClaim.sql
SysCredit.PostgreSQL/Tables/User.sql
SysCredit.PostgreSQL/Tables/UserClaim.sql
SysCredit.PostgreSQL/Tables/UserRole.sql

feat: Porting The SQLServer Database to PostgresSQL
